defaults:
  - model: detrv2_18
  - _self_
  
batch_size: 32
epochs: 10
lr: 0.0001
weight_decay: 0.0005
warmup_epochs: 5
root_dir: Fruits-detection
log : True
seed : 42
aug : hard
n_images : 6
freeze : False
patience : 5
delta : 0.001
num_workers : 4
task : det
download_data : False
lr_factor : 50