defaults:
  - model: detrv2_18
  - _self_

effective_batch_size: 64
step_batch_size : 8
epochs: 30
lr: 1e-5
weight_decay: 0.01
warmup_epochs: 5
root_dir: Fruit_dataset
log : True
seed : 42
n_images : 6
patience : 15
delta : 0.001
num_workers : 4
download_data : False
lr_back_factor : 20

ckpt:
  save : False
  load:
    model_only : False
    all : False

wait : False
info : False
min_area : 4.0
min_viz : 0.3
min_width : 2.0
min_height : 2.0
aug : hard
do_sample : True
freeze_backbone : True
partially_freeze_backbone : False
upload : False
mosaic:
  use : True
  prob : 0.8
  disable_epoch : 10
decoder_method : default
phase : 1
eta_min_factor : 10
lin_start_factor : 0.1
