defaults:
  - model: detrv2_18
  - _self_

effective_batch_size: 64
step_batch_size : 8
epochs: 30
lr: 0.0001
weight_decay: 0.01
warmup_epochs: 5
root_dir: Fruit_dataset
log : True
seed : 42
n_images : 6
patience : 15
delta : 0.001
num_workers : 4
download_data : False
lr_back_factor : 50
lr_enc_dec_factor : 5
load_ckpt : False
checkpoint : False
wait : False
info : False
min_area : 512
min_viz : 0.1
min_width : 12
min_height : 12
aug : hard
sample_strat : max
do_sample : True
freeze_backbone : True
freeze_encoder : False
partially_freeze_backbone : False

# Confidence threshold settings for debugging detection issues
conf_threshold: 0.25  # Default confidence threshold
iou_threshold: 0.45   # IoU threshold for matching detections to ground truth

# Class-specific confidence thresholds (optional)
# Format: {class_id: threshold} where class_id is 0-indexed
# Example for debugging cherry and pomegranate detection:
#class_confidence_thresholds:
  #0: 0.1   # Lower threshold for cherry (class 0)
  #1: 0.15  # Lower threshold for pomegranate (class 1)
  #2: 0.25  # Default for other classes
