defaults:
  - model: tiny_vit
  - _self_
  
batch_size: 32
epochs: 10
lr: 0.0001
weight_decay: 0.001
warmup_epochs: 5
root_dir: fruits-360
log : True
seed : 42
aug : hard
n_images : 6
input_size : 224
freeze : False
patience : 5
delta : 0.001
num_workers : 4