defaults:
  - model: detrv2_18
  - _self_
  
effective_batch_size: 64
step_batch_size : 8
epochs: 10
lr: 0.0001
weight_decay: 0.0005
warmup_epochs: 5
root_dir: Fruits-detection
log : True
seed : 42
n_images : 6
patience : 5
delta : 0.001
num_workers : 4
download_data : False
lr_factor : 50
load_ckpt : False
checkpoint : False
wait : False
info : False
min_area : 512
min_viz : 0.4
min_width : 14
min_height : 14