name: Build & Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages    
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install -e '.[dev,torch]'

      - name: Generate API stubs
        run: |
          cd docs
          sphinx-apidoc -o source ../src

      - name: Build HTML
        run: |
          cd docs
          make html

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - id: deployment
        name: Deploy to GitHub Pages
        uses: sphinx-notes/pages@v3
        with:
          documentation_path: docs
