name: Build & Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Setup Project
        run: pip install -e .
      - name: Install dependencies
        run: |
          pip install Pillow omegaconf albumentations numpy sphinx sphinx-autodoc-typehints furo

      - name: Generate API stubs
        run: |
          cd docs
          sphinx-apidoc -o source ../src

      - name: Build HTML
        run: |
          cd docs
          make html

      - name: Deploy to GitHub Pages
        uses: sphinx-notes/pages@v3
        with:
          documentation_path: docs
